PATCH  http://localhost:8080/employees/61f06f163998ec1604c641f6
Content-Type: application/json

{
    "name": "PATCH",
    "contractType": "UoP"
}

###
GET http://localhost:8080/employees/61f069b09b1bcdcd27735c21

###
DELETE http://localhost:8080/employees/61f06e2a245cb638d556ecbc

###
POST  http://localhost:8080/employees
Content-Type: application/json

{
    "name": "Maniek",
    "contractType": "UoD"
}

###
GET http://localhost:8080/employees